hub:
    image: selenium/hub
    ports:
        - "4444:4444"

chrome:
    image: selenium/node-chrome-debug
    links:
        - hub
    ports:
        - "5900:5900"

main:
    command: >
        bash -c "
        echo 'Waiting 5s to start...'
        && sleep 5s
        && ./node_modules/.bin/nightwatch --env=default
        "
    image: justinanastos/hgtv
    links:
        - chrome
        - hub
    volumes:
        - ./index.js:/usr/src/app/index.js
        - ./tests/:/usr/src/app/tests/
        - ./utils/:/usr/src/app/utils/
        - ./nightwatch.conf.js:/usr/src/app/nightwatch.conf.js
