hub:
    environment:
        - SE_OPTS=-debug
    image: selenium/hub:2.50.0
    ports:
        - "4444:4444"

chrome:
    links:
        - "hub:hub"
    image: selenium/node-chrome:2.50.0

main:
    image: justinanastos/hgtv
    links:
        - "chrome:hub"
    volumes:
        - ./.babelrc:/usr/src/app/.babelrc
        - ./index.js:/usr/src/app/index.js
